### ISSUE TITLE
Tests have flaky results?

### ISSUE THREAD

**Issue by davcri** [toolx-dev/toolx#3]
I noticed that running tests via `npm run test` multiple times may give different results. 
It could be due to temporary folders not being cleaned up after each run?

**How to reproduce**: 

```sh
git clone git@github.com:toolx-dev/toolx.git
cd toolx
npm i

# "/var/folders/pq/9xy5bw4s2yzd5q5sxsr029km0000gn/T" is the temp dir on my system
ls -d /var/folders/pq/9xy5bw4s2yzd5q5sxsr029km0000gn/T/{tool*,Tool*}

# cleanup tmp dirs
rm /var/folders/pq/9xy5bw4s2yzd5q5sxsr029km0000gn/T/{tool*,Tool*}

# first run 
npm run test # 3 tests failing

# next run
npm run test # 2 tests failing
```

<details><summary>First run output</summary>
<pre>
 ❯ packages/core/test/Tool.server.test.js (8)
   ❯ Tool class (8)
     ✓ should create an instance of Tool
     ✓ should have options initialized
     × should check if create dir and path exists
     ✓ should create a directory if it does not exist
     ✓ should change the file extension
     ✓ should remove specified files
     × should run the tool logic
     × should run the tool logic with arguments on constructor
 ✓ packages/core/test/Base.test.js (11)
 ✓ packages/svg/test/ToolSvg.test.js (2)
 ✓ packages/sharp/test/ToolSharp.test.js (2)
 ✓ packages/combine/test/ToolCombine.test.js (2)
 ✓ packages/json/test/ToolJSON.test.js (2)
 ✓ packages/core/test/Event.test.js (2)
 ✓ packages/core/test/Pipeline.test.js (3)
 ✓ packages/imagemin/test/ToolImagemin.test.js (1)
 ✓ packages/remove/test/ToolRemove.test.js (1)
</pre>
</details> 

<details><summary>Second run</summary>
<pre>
 ❯ packages/core/test/Tool.server.test.js (8)
   ❯ Tool class (8)
     ✓ should create an instance of Tool
     ✓ should have options initialized
     ✓ should check if create dir and path exists
     ✓ should create a directory if it does not exist
     ✓ should change the file extension
     ✓ should remove specified files
     × should run the tool logic
     × should run the tool logic with arguments on constructor
 ✓ packages/core/test/Base.test.js (11)
 ✓ packages/svg/test/ToolSvg.test.js (2)
 ✓ packages/sharp/test/ToolSharp.test.js (2)
 ✓ packages/combine/test/ToolCombine.test.js (2)
 ✓ packages/json/test/ToolJSON.test.js (2)
 ✓ packages/core/test/Event.test.js (2)
 ✓ packages/core/test/Pipeline.test.js (3)
 ✓ packages/imagemin/test/ToolImagemin.test.js (1)
 ✓ packages/remove/test/ToolRemove.test.js (1)
</pre>
</details> 

Tested on 256e53c339a8a98ddc4ff1f8b7dc41f54db35426 , MacBook Air M1

**Comment by williammanco** [comment]
Mmm yep  @davcri no happened to me but works weirdly with Github Actions (like your tests), i think is related to tmp folder... but need to check better or explore more things about tests with files. 🧶 I'll try with codesandbox
